spring:
  profiles:
    active: local
  application:
    name: SpringWb
  cloud:
    loadbalancer:
      enabled: true
    consul:
      host: localhost # Consul 服务器的主机地址
      port: 8500 # Consul 服务器的端口
      discovery:
        prefer-ip-address: true # 优先使用服务 IP 地址进行注册
        service-name: ${spring.application.name} # 使用 Spring 应用名作为服务名进行注册
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_data?useSSL=false&characterEncoding=UTF-8
    username: your_db_username
    password: your_db_password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: resumedb
      username: your_mongodb_username
      password: your_mongodb_password
      authentication-database: admin
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000 # 使用毫秒格式，兼容 Redis Lettuce
      password: Alone117
      lettuce:
        pool:
          max-active: 20 # 最大连接数
          max-wait: -1 # 最大阻塞等待时间(负数表示无限制)
          max-idle: 5 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数
  mail:
    host: smtp.163.com # 你邮箱的smtp地址
    username: your_email@example.com # 申请了smtp的邮箱
    password: your_smtp_password # SMTP服务的秘钥
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# MinIO配置
minio:
  endpoint: http://127.0.0.1:18988
  accessKey: your_minio_access_key
  secretKey: your_minio_secret_key
  bucketName: default-bucket
  # 可选配置
  secure: false # 如果使用HTTPS则设为true
  connectTimeout: 10000 # 连接超时时间(毫秒)
  readTimeout: 10000 # 读取超时时间(毫秒)

application:
  security:
    jwt:
      secret-key: your_jwt_secret_key_here # 请替换为安全的随机字符串
      expiration: 86400000 # JWT 过期时间，1 天（毫秒）
      refresh-token:
        expiration: 604800000 # 刷新令牌过期时间，7 天（毫秒）

server:
  error:
    whitelabel:
      enabled: false # 禁用 Spring 默认错误页面
  port: 8080

logging:
  level:
    root: INFO
    "[org.springframework.boot.autoconfigure]": WARN
    "[org.springframework]": WARN
    "[com.david.hlp.Spring.system.mapper]": WARN
    "[org.mybatis]": WARN
    "[com.david.hlp.Spring.boss]": WARN
    "[com.david.hlp.Spring.common.util.aspect]": WARN
    "[com.david.hlp.Spring.common.util.datasource]": WARN
    "[org.springframework.jdbc]": WARN

# HDFS配置
hadoop:
  hdfs:
    uri: hdfs://hadoop-single:9000
    user: root

# HDFS日志缓存配置
hdfs:
  log:
    cache:
      threshold: 100 # 缓存日志条数阈值，达到后批量写入
    flush:
      interval: 30000 # 强制刷新间隔（毫秒），即使未达到阈值

# MyBatis & MyBatis-Plus 配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
    # cache-enabled: false
  mapper-locations: classpath*:/mapper/**/*.xml
