spring:
  profiles:
    active: local
  application:
    name: spring-crawler
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boss_data?useSSL=false&characterEncoding=UTF-8
    username: your_db_username
    password: your_db_password
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: your_redis_password
  ai:
    ollama:
      base-url: http://localhost:11434 # Ollama 服务地址
      chat:
        options:
          model: qwen3:4b # 指定使用 qwen3:4b 模型
          format: json # 建议模型返回 JSON 格式
server:
  port: 8081

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.david.hlp.crawler.boss.entity

webdriver:
  chrome:
    driver: /path/to/chromedriver
    headless: true