spring:
  application:
    name: SpringBootWork
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_data?useSSL=false&characterEncoding=UTF-8
    username: root
    password: Alone117
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  mail:
    outTime: 15
    host: smtp.163.com # 你邮箱的smtp地址
    username: davidblog117@163.com # 申请了smtp的邮箱
    password: VIBXJWEUSYVJMJXK # SMTP服务的秘钥
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000 # 使用毫秒格式，兼容 Redis Lettuce
      password: Alone117
      lettuce:
        pool:
          max-active: 20  # 最大连接数
          max-wait: -1    # 最大阻塞等待时间(负数表示无限制)
          max-idle: 5     # 最大空闲连接数
          min-idle: 0     # 最小空闲连接数

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # JWT 过期时间，1 天（毫秒）
      refresh-token:
        expiration: 604800000 # 刷新令牌过期时间，7 天（毫秒）

server:
  error:
    whitelabel:
      enabled: false # 禁用 Spring 默认错误页面
  port: 8080

logging:
  level:
    org.springframework.boot.autoconfigure: OFF
    # org.springframework: DEBUG
    # com.david.hlp.Spring.system.mapper: TRACE
    # org.mybatis: DEBUG
    # com.david.hlp.Spring.boss: INFO
    # com.david.hlp.Spring.common.util.aspect: DEBUG
    # com.david.hlp.Spring.common.util.datasource: DEBUG
    # org.springframework.jdbc: DEBUG
  file:
    name: /home/david/Project/BlogAndChart/logs/spring.log # 主日志文件路径

# MyBatis & MyBatis-Plus 配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
    type-enums-package: com.david.hlp.SpringBootWork.system.token
    # cache-enabled: false
  mapper-locations: classpath*:/mapper/**/*.xml
  # type-aliases-package: com.david.hlp.Spring.**.entity

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: Asia/Shanghai
  serialization:
    write-dates-as-timestamps: false
  deserialization:
    fail-on-unknown-properties: false